В блоке `try` выполняется задача, если в этом блоке есть ошибка тогда выполняется задача в блоке `catch`.